# Generated by Django 5.1.1 on 2024-10-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedpaper',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
    ]
