# Generated by Django 5.1.1 on 2024-10-30 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_reviewer_scrapedpaper_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedpaper',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='myapp.reviewer'),
        ),
    ]
