# Generated by Django 5.1.1 on 2024-11-06 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_scrapedpaper_reviewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapedpaper',
            name='first_author',
        ),
        migrations.AddField(
            model_name='scrapedpaper',
            name='authors',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='scrapedpaper',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='DetailReviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='NULL', max_length=255)),
                ('email', models.EmailField(default='NULL', max_length=255)),
                ('orcid', models.CharField(default='NULL', max_length=255)),
                ('username', models.CharField(default='NULL', max_length=255)),
                ('reviewer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='myapp.reviewer')),
            ],
        ),
    ]
