# Generated by Django 5.1.1 on 2024-11-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_scrapedpaper_first_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailreviewer',
            name='affiliation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
